baseURL = "https://philippbruhns.com"
title = "Philipp Bruhns"
theme = "gokarna"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true

# Choose one of emacs, trac or perldoc
pygmentsStyle = "monokai"

[params]
  footer = "Philipp Bruhns"
  description = "Student | Engineer"
  avatarURL = "/images/plant.jpg"
  AvatarAltText = "avatar"
  avatarSize = "size-xl"
  accentColor = "#649b41"

  socialIcons = [
    {name = "linkedin", url = "https://www.linkedin.com/in/philipp-bruhns-7593ba235"},
    {name = "github", url = "https://github.com/YodaImperium"},
    {name = "spotify", url = "https://open.spotify.com/user/yodaimperium?si=f7c5c7023a3b46b0"},
  ]
  metaKeywords = ["blog", "gokarna", "hugo"]

[menu]
  [[menu.main]]
    name = ""
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    name = ""
    pre = "<span data-feather='code'></span>"
    url = "/projects/"
    weight = 3

  [[menu.main]]
    identifier = "github"
    pre = "<span data-feather='github'></span>"
    url = "https://github.com/YodaImperium/philippbruhns.com/"
    weight = 5

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false